apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ required "Must provide a storage class name." .Values.storageClass.name}}-xfs
  annotations:
provisioner: csi-vxflexos
reclaimPolicy: {{ required "Must provide a storage class reclaim policy." .Values.storageClass.reclaimPolicy }}
parameters:
  storagepool: {{ required "Must provide a VxFlex OS storage pool name." .Values.storagePool }}
  FsType: xfs
